#!/usr/bin/env bash
# setup-server.sh — bootstrap a fresh Ubuntu 22.04 host into a
# Le Cobol production server.
#
# Run on the target host:
#     sudo bash deploy/setup-server.sh
#
# The script is idempotent: running it again on an already-set-up
# host leaves it in the same state (apt install is a no-op,
# a2enmod skips already-enabled modules, the env file is only
# generated on first run, etc.).
#
# What it does, in order:
#   1. Install the apt packages we need (GnuCOBOL, Ghostscript,
#      Apache + certbot, curl, jq, rsync, make, git, ufw).
#   2. Enable the Apache modules required for CGI + TLS +
#      header rewriting, and switch the MPM to prefork (CGI is
#      fork-per-request, so prefork is the right pairing).
#   3. Create a "cobill" system user that owns the install root.
#   4. Lay out /opt/cobill/{bin,data,pdf,web,src/postscript,lib}.
#   5. Wire symlinks inside bin/ so that COBOL programs running
#      with cwd=/opt/cobill/bin/ can use the relative paths
#      "data/", "pdf/", "src/" and "lib/" exactly as they do
#      in development.
#   6. Install the Apache vhost from deploy/cobill.conf.
#   7. Open the firewall on 22 / 80 / 443.
#   8. Generate a random admin password, hash it with
#      sha512crypt, persist only the hash, and print the
#      plaintext exactly once for the operator to save.
#   9. Make Apache source the env file at startup so PassEnv
#      can surface COBILL_AUTH_HASH to the CGI processes.
#   10. Reload Apache.
#
# After this script, the operator runs:
#     scripts/deploy.sh user@host
#     sudo certbot --apache -d cobill.your-domain.tld

set -euo pipefail

# Setting up a system-wide install requires root.
if [[ $EUID -ne 0 ]]; then
    echo "Run me as root (sudo bash deploy/setup-server.sh)." >&2
    exit 1
fi

# Filesystem layout used by every later step.
INSTALL_ROOT="/opt/cobill"
DATA_ROOT="${INSTALL_ROOT}/data"
PDF_ROOT="${INSTALL_ROOT}/pdf"
WEB_ROOT="${INSTALL_ROOT}/web"
BIN_ROOT="${INSTALL_ROOT}/bin"
APP_USER="cobill"

# Tiny logger used by the rest of the script. Cyan arrow prefix
# makes the steps easy to scan.
log() { printf "\n\033[1;36m==>\033[0m %s\n" "$*"; }

# ---- 1. System packages -----------------------------------------------
log "Installing GnuCOBOL, Ghostscript, Apache, certbot"
# DEBIAN_FRONTEND=noninteractive prevents apt from prompting
# (e.g. for the Postfix mail configuration that gets pulled in
# as an indirect dependency on some images).
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    gnucobol \
    ghostscript \
    apache2 \
    certbot python3-certbot-apache \
    curl \
    jq \
    rsync \
    make \
    git \
    ca-certificates \
    ufw

# ---- 2. Apache modules ------------------------------------------------
log "Enabling Apache modules"
# cgi      : runs binaries on ScriptAlias directories
# headers  : Header set X-Frame-Options ... in the vhost
# rewrite  : currently unused but cheap to enable
# ssl      : required by certbot's vhost rewrite later
a2enmod cgi headers rewrite ssl >/dev/null

# Switch from the event MPM (Apache's default, optimised for
# long-lived workers and keep-alive) to prefork. Each prefork
# worker handles one request at a time, fork()s, then exec()s
# the CGI binary, which is exactly what we want here.
a2dismod -q mpm_event 2>/dev/null || true
a2enmod  -q mpm_prefork

# ---- 3. App user ------------------------------------------------------
# System user (no login shell, home pointed at the install
# root). Owns the source tree and runs the COBOL build.
if ! id "${APP_USER}" >/dev/null 2>&1; then
    log "Creating system user ${APP_USER}"
    useradd --system --home-dir "${INSTALL_ROOT}" \
            --shell /usr/sbin/nologin "${APP_USER}"
fi

# ---- 4. Filesystem layout ---------------------------------------------
log "Creating ${INSTALL_ROOT} layout"
mkdir -p "${INSTALL_ROOT}" "${BIN_ROOT}" "${DATA_ROOT}" "${PDF_ROOT}" \
         "${WEB_ROOT}" "${INSTALL_ROOT}/src/postscript" \
         "${INSTALL_ROOT}/lib"

# Permissions strategy:
#   /opt/cobill/*           owned by cobill:cobill (default)
#   /opt/cobill/data/       group=www-data so Apache can write
#   /opt/cobill/pdf/        group=www-data, same reason
#
# chmod 2775 = rwxrwsr-x. The leading 2 is the SGID bit: every
# file created under the directory inherits the directory's
# group, which means PDFs generated by the CGI binary stay
# readable+writable for both cobill (for cleanup) and www-data
# (for Apache to serve them).
chown -R "${APP_USER}:${APP_USER}" "${INSTALL_ROOT}"
chgrp -R www-data "${DATA_ROOT}" "${PDF_ROOT}"
chmod -R 2775 "${DATA_ROOT}" "${PDF_ROOT}"

# ---- 5. CWD-relative symlinks -----------------------------------------
# The COBOL SELECT clauses use relative paths like "data/clients.dat"
# because that is what the dev layout looks like. Apache runs the
# CGI binaries with cwd=/opt/cobill/bin, so we make those relative
# paths resolve by symlinking from inside bin/.
log "Wiring relative-path symlinks in ${BIN_ROOT}"
ln -sfn "${DATA_ROOT}"          "${BIN_ROOT}/data"
ln -sfn "${PDF_ROOT}"           "${BIN_ROOT}/pdf"
ln -sfn "${INSTALL_ROOT}/src"   "${BIN_ROOT}/src"
ln -sfn "${INSTALL_ROOT}/lib"   "${BIN_ROOT}/lib"

# ---- 6. Apache vhost --------------------------------------------------
VHOST_FILE="/etc/apache2/sites-available/cobill.conf"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ -f "${SCRIPT_DIR}/cobill.conf" ]]; then
    log "Installing Apache vhost"
    # install -m 0644 = cp with explicit mode. Owner stays root
    # which is the right thing for files under /etc/apache2.
    install -m 0644 "${SCRIPT_DIR}/cobill.conf" "${VHOST_FILE}"
else
    echo "(skipped vhost install: cobill.conf not in ${SCRIPT_DIR})"
fi

# Disable the default "It works!" site and enable ours.
a2dissite -q 000-default 2>/dev/null || true
a2ensite -q cobill

# ---- 7. Firewall -----------------------------------------------------
# Open the three ports we need before enabling UFW, so an SSH
# session is never locked out mid-config.
log "UFW: allow 22/80/443 then enable"
ufw allow 22/tcp comment 'ssh'    || true
ufw allow 80/tcp comment 'http'   || true
ufw allow 443/tcp comment 'https' || true
ufw --force enable                || true
ufw status verbose                || true

# ---- 8. Initial admin credential -------------------------------------
# Only ever runs on the very first setup-server.sh invocation.
# A subsequent run leaves the existing /etc/cobill/cobill.env
# alone (so the operator does not rotate the password by
# accident).
ENV_FILE="/etc/cobill/cobill.env"
if [[ ! -f "${ENV_FILE}" ]]; then
    log "Generating /etc/cobill/cobill.env"
    mkdir -p /etc/cobill
    # Generate ~20 alphanumeric chars; tr drops the URL-unsafe
    # bytes that base64 may produce.
    PASS="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
    # -6 selects the sha512crypt algorithm. openssl picks the
    # salt automatically.
    HASH="$(openssl passwd -6 "${PASS}")"
    # IMPORTANT: single-quote the hash. /etc/apache2/envvars
    # sources its env file through bash, and a bare hash like
    # $6$salt$... would have $6, $s, etc. interpreted as
    # positional parameters and silently stripped.
    cat > "${ENV_FILE}" <<EOF
COBILL_AUTH_HASH='${HASH}'
EOF
    # root:www-data with mode 0640 lets Apache read the file
    # at startup (so PassEnv can pick the var up) while keeping
    # the hash unreadable to other users on the host.
    chown root:www-data "${ENV_FILE}"
    chmod 0640 "${ENV_FILE}"
    echo
    echo "  ----------------------------------------------------------"
    echo "  Initial admin password (shown once, save it now):"
    echo "  ${PASS}"
    echo "  ----------------------------------------------------------"
fi

# ---- 9. Make Apache source the env file ------------------------------
# /etc/apache2/envvars is sourced by the apache2ctl wrapper
# before Apache starts. We append a block that pulls in
# /etc/cobill/cobill.env (set -a exports every var defined in
# the source).
ENVVARS_FILE="/etc/apache2/envvars"
if ! grep -q "cobill.env" "${ENVVARS_FILE}"; then
    log "Wiring /etc/cobill/cobill.env into ${ENVVARS_FILE}"
    cat >> "${ENVVARS_FILE}" <<'EOF'

if [ -f /etc/cobill/cobill.env ]; then
    set -a
    . /etc/cobill/cobill.env
    set +a
fi
EOF
fi

# ---- 10. Restart Apache ----------------------------------------------
# configtest first so a typo in the vhost makes the script fail
# instead of taking the server down.
log "Reloading Apache"
apachectl configtest
# reload preserves in-flight connections; if Apache is not
# running yet, fall back to a hard restart.
systemctl reload apache2 || systemctl restart apache2

cat <<MSG

Setup complete.

Next:
    scripts/deploy.sh user@${HOSTNAME:-your-host}
    sudo certbot --apache -d cobill.your-domain.tld
    curl -i https://cobill.your-domain.tld/login.html

MSG
